import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          Iphone141SignInPage(),
        ]),
      ),
    );
  }
}

class Iphone141SignInPage extends StatelessWidget {
  const Iphone141SignInPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              const Positioned(
                left: 82,
                top: 175,
                child: SizedBox(
                  width: 219,
                  height: 83,
                  child: Text(
                    'BREW',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 75,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w100,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 60,
                top: 333,
                child: SizedBox(
                  width: 272,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 272,
                          height: 44,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF6C584C),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(30),
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 22,
                        top: 11,
                        child: SizedBox(
                          width: 223,
                          height: 27,
                          child: Text(
                            'Create Account',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Public Sans',
                              fontWeight: FontWeight.w100,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 82,
                top: 546,
                child: SizedBox(
                  width: 223,
                  height: 27,
                  child: Text(
                    'Phone Number',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Public Sans',
                      fontWeight: FontWeight.w100,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 82,
                top: 511,
                child: SizedBox(
                  width: 223,
                  height: 27,
                  child: Text(
                    'Sign in with',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFFA98467),
                      fontSize: 20,
                      fontFamily: 'Public Sans',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 133,
                top: 546,
                child: TextButton(
                  onPressed: () {},
                  child: Container(
                    width: 42,
                    height: 42,
                    decoration: const BoxDecoration(
                      image: DecorationImage(
                        image: AssetImage("assets/gmail.png"),
                        fit: BoxFit.fill,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 200,
                top: 549,
                child: TextButton(
                  onPressed: () {},
                  child: Container(
                    width: 35,
                    height: 35,
                    decoration: const BoxDecoration(
                      image: DecorationImage(
                        image: AssetImage("assets/phone.png"),
                        fit: BoxFit.fill,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 452,
                child: Container(
                  width: 302,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFA98467),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
